GET http://localhost:3000/api/users HTTP/1.1
###
GET http://localhost:3000/api/tarea HTTP/1.1
###
GET http://localhost:3000/api/login HTTP/1.1
###
POST http://localhost:3000/api/users HTTP/1.1 

###

POST http://localhost:3000/api/users/
Content-Type: application/json

  {
  "id": 1,
  "usuario": "alan1",
  "nombre": "Cinthya",
  "apellido": "Gonzalez",
  "correo": "cinthya.gonzalez@iteso.mx",
  "fecha": "04/03/2002",
  "sexo": "M",
  "imagen": "https://randomuser.me/api/portraits/women/5.jpg",
  "password": "gupi",
  "token": "token",
}

###
GET http://localhost:3000/api/users/10
  

# GET http://localhost:3000/api/tarea HTTP/1.1

# GET http://localhost:3000/api/login HTTP/1.1

# POST http://localhost:3000/api/users HTTP/1.1 