GET http://localhost:3000/api/users HTTP/1.1
###
GET http://localhost:3000/api/tarea HTTP/1.1
###
GET http://localhost:3000/api/login HTTP/1.1
###
POST http://localhost:3000/api/users HTTP/1.1 

###

POST http://localhost:3000/api/users/
Content-Type: application/json

  {
  "id": 1,
  "usuario": "cinthya1",
  "nombre": "Cinthya",
  "apellido": "Gonzalez",
  "correo": "cinthya.gonzalez@iteso.mx",
  "fecha": "04/03/2002",
  "sexo": "M",
  "imagen": "https://randomuser.me/api/portraits/women/5.jpg",
  "password": "gupi"
}

###
GET http://localhost:3000/api/users/10
###
DELETE  http://localhost:3000/api/users/11
###
PUT  http://localhost:3000/api/users/10
Content-Type: application/json

  {
    "id":"10",
    "nombre": "lupeee",
    "apellido": "lopez",
    "usuario": "valrmzl",
    "password": "pepee<3",
    "imagen":"https://randomuser.me/api/portraits/women/5.jpg"

  }


###

POST http://localhost:3000/api/login HTTP/1.1 
Content-Type: application/json

{
    "user": "naim2206",
    "pass": "123" 
}

# GET http://localhost:3000/api/tarea HTTP/1.1

# GET http://localhost:3000/api/login HTTP/1.1


###
POST http://localhost:3000/api/users HTTP/1.1 

###
POST  http://localhost:3000/api/tarea  
Content-Type: application/json

{
  "fecha": "2022-11-25",
  "tags": ["URGENT", "REQUIRED"],
  "completed": "false",
  "usuarios": ["Ana", "Naim", "Val"],
  "descripcion": "Proyecto final web"
}

###

GET http://localhost:3000/api/tarea HTTP/1.1


###
DELETE  http://localhost:3000/api/tarea/6383ef6eb6f46b1e78ab586c HTTP/1.1
Content-Type: application/json


###
PUT  http://localhost:3000/api/tarea/  HTTP/1.1
Content-Type: application/json

{
  "id": "1073610702417",
  "date": "2022-12-01",
  "description": "Proyecto final web",
  "tags": "WORK",
  "users": "Naim",
  "completed": "false"
}
###

PUT  http://localhost:3000/api/tarea/done/345516675356  HTTP/1.1




###



POST http://localhost:3000/api/users/
Content-Type: application/json

  {
  "id": 2,
  "usuario": "ana",
  "nombre": "ana",
  "apellido": "naim2",
  "correo": "naim@naim.com",
  "fecha": "04/03/2002",
  "sexo": "H",
  "imagen": "https://randomuser.me/api/portraits/women/5.jpg",
  "password": "123"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

  {
  "user": "naim2",
  "pass": "123"
}